import { createContext, useContext, useState, ReactNode } from "react";

type Language = "fr" | "en";

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  fr: {
    welcome: "🎉 Bienvenue dans l'Atelier IA Ludique !",
    subtitle: "Joue, découvre l'intelligence artificielle, et défie une IA !",
    startAdventure: "👉 Commencer l'aventure !",
    chooseGame: "🕹️ Choisis ton jeu et ton mode !",
    chooseGameSubtitle: "Chaque jeu propose 3 façons de jouer avec l'IA. À toi de choisir !",
    whereIsCharlie: "🧍 Où est Charlie",
    dobble: "🔍 Dobble",
    dinoRun: "🦖 Dino Run",
    modeAIPure: "🤖 Mode IA Pure",
    modeAIVsHuman: "🧠 Mode IA vs Humain",
    modeExplicatif: "📚 Mode Explicatif",
    descAIPure: "Laisse l'IA te montrer ce qu'elle sait faire !",
    descAIVsHuman: "Défie l'IA en duel !",
    descExplicatif: "Découvre les secrets de l'intelligence artificielle",
    descDinoAIVsHuman: "Contrôle le dinosaure avec tes gestes !",
    descDinoExplicatif: "Comprends comment l'IA détecte tes mouvements",
    launchGame: "✅ Lancer le jeu",
    backHome: "Accueil",
    selectGame: "Sélectionne un jeu pour continuer",
    selectMode: "Choisis un mode de jeu",
    gestureDetected: "Geste détecté",
    handPosition: "Position de la main",
    confidence: "Confiance",
    thresholds: "Seuils de détection",
    finalScore: "Score final",
    replay: "Rejouer",
    home: "Accueil",
    explainProcess: "Explication du processus",
    howDidAIAnalyze: "Comment l'IA a-t-elle analysé ?",
    aiProcessExplanation: "Découvre étape par étape comment l'IA a détecté l'élément",
    step: "Étape",
    next: "Suivant",
    previous: "Précédent",
    finish: "Terminer",
    step1Title: "Pré-traitement de l'image",
    step1Desc: "L'image est redimensionnée et normalisée pour optimiser la détection. Les pixels sont convertis en valeurs numériques que l'IA peut traiter.",
    step2Title: "Extraction des caractéristiques",
    step2Desc: "Un réseau de neurones convolutif (CNN) analyse l'image couche par couche pour détecter les formes, les couleurs et les textures.",
    step3Title: "Détection et localisation",
    step3Desc: "L'IA identifie les éléments dans l'image et calcule leur position exacte avec des boîtes englobantes (bounding boxes).",
    step4Title: "Classification et scoring",
    step4Desc: "Chaque élément détecté reçoit un score de confiance. Seuls les résultats dépassant un seuil minimum sont retenus.",
    step5Title: "Post-traitement",
    step5Desc: "Les détections redondantes sont supprimées et les résultats finaux sont affinés pour garantir la précision maximale.",
    analyzing: "Analyse en cours…",
    analysisComplete: "Analyse terminée !",
    aiSearching: "L'IA cherche l'élément cible…",
    aiFoundElements: "L'IA a trouvé tous les éléments !",
    continueGoodWork: "Continue comme ça !",
    explanatoryMode: "Mode Explicatif",
    explanatoryModeDebug: "Mode Explicatif - Debug",
    explanatoryModePreparation: "📚 Mode Explicatif – Préparation",
    aiPurePreparation: "🤖 Mode IA Pure – Préparation",
    aiVsHumanPreparation: "⚔️ IA vs Humain – Préparation",
    aiPurePreparationDesc: "Choisis comment l'IA va analyser ton image",
    aiVsHumanPreparationDesc: "Prépare le terrain pour défier l'IA",
    explanatoryPreparationDesc: "Charge une image pour comprendre le processus",
    originalImage: "Image originale",
    normalizedImage: "Image normalisée",
    neuralLayersActive: "Couches neuronales actives",
    detected: "Détecté",
    detectionConfidence: "Confiance détection",
    localizationPrecision: "Précision localisation",
    minimumThreshold: "Seuil minimum",
    duplicates: "Doublons",
    finalResult: "Résultat final",
    gesture: "Geste",
    action: "Action",
    noHandDetected: "Aucune main détectée",
    capturedImage: "Image capturée",
    cameraPreview: "Aperçu caméra",
    back: "Retour",
    capture: "📸 Capturer",
    launchAnalysis: "✅ Lancer l'analyse",
    backToHome: "Retour à l'accueil",
    aiFinished: "L'IA a terminé ! À toi de jouer !",
    yourTurn: "À toi de jouer !",
    gameInProgress: "Partie en cours...",
    charlieDetected: "Charlie détecté ✓",
    commonSymbolDetected: "Symbole en commun détecté ✓",
    missionAccomplished: "Mission accomplie !",
    recapture: "Recapturer",
    changeImage: "Changer d'image",
    nextMode: "Passer au mode suivant",
    aiResults: "📊 Résultats IA",
    confidenceScore: "Score de confiance",
    processingTime: "⏱️ Temps de traitement",
    detectedElements: "🎯 Éléments détectés",
    // Dino Tutorial - Training Step
    step3TrainingTitle: "L'Entraînement du Cerveau",
    step3TrainingDesc: "Comment l'IA sait ce qu'est une main ouverte ? Elle a appris en analysant des milliers d'exemples !",
    trainingVsInference: "Entraînement vs Inférence",
    trainingAnalogy: "Comme un étudiant qui révise (Entraînement) puis passe l'examen (Inférence).",
    frozenModel: "Cerveau Figé",
    frozenModelDesc: "Le fichier .tflite est le résultat final : un modèle optimisé qui ne change plus.",
    neuralNetwork: "Réseau de Neurones",
    layersExplanation: "Les 42 coordonnées traversent des couches de neurones mathématiques pour calculer le score final.",
    bestConfidence: "🎯 Meilleure confiance",
    // Dino Tutorial
    computerVisionTitle: "La Vision par Ordinateur",
    whatIsComputerVision: "Qu'est-ce que c'est ?",
    computerVisionExplanation: "La vision par ordinateur est la capacité d'une machine à \"voir\". Contrairement à nous, elle ne voit pas une \"image\", mais une grille de chiffres (pixels). Son but est de trouver du sens dans ces chiffres.",
    analogy: "💡 Analogie :",
    analogyText: "C'est comme lire une partition de musique : vous voyez des symboles, mais votre cerveau entend la mélodie.",
    step1Skeleton: "Étape 1 : Le Squelette",
    handDetection: "Détection de la Main",
    mediaPipeExplanation: "Nous utilisons une IA appelée MediaPipe. Elle ne regarde pas la couleur de votre peau ou la forme de vos bagues. Elle cherche 21 points précis (les phalanges, le poignet, le bout des doigts).",
    tryMovingHand: "Essayez de bouger votre main !",
    detectedWithIcon: "Détecté",
    waitingForHand: "En attente...",
    raiseHand: "Levez votre main devant la caméra...",
    step2Classification: "Étape 2 : La Classification",
    shapeRecognition: "Reconnaissance de Forme",
    shapeComparison: "L'IA ne mesure pas juste une distance. Elle compare la forme globale de main. C'est comme un jeu d'enfant : \"Est-ce que cette forme rentre dans la boîte Main Ouverte ou Poing Fermé ?\"",
    classOpen: "CLASSE : OUVERT",
    classRest: "CLASSE : REPOS (COURIR)",
    open: "OUVERT",
    rest: "REPOS",
    input: "ENTRÉE",
    step3Action: "Étape 3 : L'Action",
    trigger: "Le Déclencheur",
    changeDetection: "Le jeu ne regarde pas juste la forme, mais le changement (Front Montant). Action = État Précédent ≠ État Actuel",
    actionInstruction: "Alternez \"Main Ouverte\" (Saut) et \"Poing Fermé\" (Repos) !",
    jumps: "SAUTS",
    before: "AVANT",
    now: "MAINTENANT",
    jump: "SAUT !!!",
    waitingAction: "EN ATTENTE D'ACTION...",
    bonusConfidence: "Bonus : Confiance de l'IA",
    confidenceScoreTitle: "Score de Confiance",
    confidenceExplanation: "L'IA doute parfois. Elle calcule un pourcentage de certitude. Si la confiance est trop basse (ex: < 60%), on ignore le geste pour éviter les bugs.",
    confidenceLabel: "CONFIANCE",
    visualizationMode: "MODE_VISUALISATION : ACTIF",
    startDinoGame: "COMMENCER LE JEU",
    gameOver: "Partie Terminée !",
    finalScoreLabel: "Score final :",
    modeNotAvailable: "Mode non disponible",
    modeRequiresCamera: "Le mode 'IA vs Humain' pour Dobble nécessite l'utilisation de la caméra en temps réel.",
    modeNotSupported: "Le mode \"{mode}\" n'est pas supporté.",
    dobbleDuelBoxTitle: "⚔️ IA vs Humain – Dobble Duel !",
    dobbleDuelObjective: "Trouve le symbole commun plus vite que l'IA !",
    aiZone: "🤖 Zone IA",
    yourZone: "👤 Ta Zone",
    wrongSymbol: "❌ Mauvais symbole ! Réessaie",
    changeMode: "Changer de mode",
    results: "🏆 Résultats",
    youWon: "Tu as gagné !",
    aiWon: "L'IA a gagné !",
    draw: "Égalité !",
    aiTime: "⏱️ Temps IA",
    yourTime: "⏱️ Ton temps",
    difference: "📊 Différence",
    commonSymbol: "Symbole commun",
    takePhoto: "Prends une photo",
    realTime: "Temps réel",
    realTimeDesc: "L'IA analysera en temps réel ce qu'elle voit",
  },
  en: {
    welcome: "🎉 Welcome to the AI Fun Workshop!",
    subtitle: "Play, discover artificial intelligence, and challenge an AI!",
    startAdventure: "👉 Start the adventure!",
    chooseGame: "🕹️ Choose your game and mode!",
    chooseGameSubtitle: "Each game offers 3 ways to play with AI. Your choice!",
    whereIsCharlie: "🧍 Where's Waldo",
    dobble: "🔍 Dobble",
    dinoRun: "🦖 Dino Run",
    modeAIPure: "🤖 Pure AI Mode",
    modeAIVsHuman: "🧠 AI vs Human Mode",
    modeExplicatif: "📚 Explanatory Mode",
    descAIPure: "Let the AI show you what it can do!",
    descAIVsHuman: "Challenge the AI in a duel!",
    descExplicatif: "Discover the secrets of artificial intelligence",
    descDinoAIVsHuman: "Control the dinosaur with your gestures!",
    descDinoExplicatif: "Understand how AI detects your movements",
    launchGame: "✅ Launch game",
    backHome: "Home",
    selectGame: "Select a game to continue",
    selectMode: "Choose a game mode",
    gestureDetected: "Gesture detected",
    handPosition: "Hand position",
    confidence: "Confidence",
    thresholds: "Detection thresholds",
    finalScore: "Final score",
    replay: "Replay",
    home: "Home",
    explainProcess: "Process Explanation",
    howDidAIAnalyze: "How did the AI analyze?",
    aiProcessExplanation: "Discover step by step how the AI detected the element",
    step: "Step",
    next: "Next",
    previous: "Previous",
    finish: "Finish",
    step1Title: "Image Preprocessing",
    step1Desc: "The image is resized and normalized to optimize detection. Pixels are converted into numerical values that the AI can process.",
    step2Title: "Feature Extraction",
    step2Desc: "A Convolutional Neural Network (CNN) analyzes the image layer by layer to detect shapes, colors, and textures.",
    step3Title: "Detection and Localization",
    step3Desc: "The AI identifies elements in the image and calculates their exact position with bounding boxes.",
    step4Title: "Classification and Scoring",
    step4Desc: "Each detected element receives a confidence score. Only results exceeding a minimum threshold are retained.",
    step5Title: "Post-processing",
    step5Desc: "Redundant detections are removed and final results are refined to ensure maximum accuracy.",
    analyzing: "Analyzing…",
    analysisComplete: "Analysis Complete!",
    aiSearching: "The AI is searching for the target element…",
    aiFoundElements: "The AI has found all elements!",
    continueGoodWork: "Keep it up!",
    explanatoryMode: "Explanatory Mode",
    explanatoryModeDebug: "Explanatory Mode - Debug",
    explanatoryModePreparation: "📚 Explanatory Mode – Preparation",
    aiPurePreparation: "🤖 Pure AI Mode – Preparation",
    aiVsHumanPreparation: "⚔️ AI vs Human – Preparation",
    aiPurePreparationDesc: "Choose how the AI will analyze your image",
    aiVsHumanPreparationDesc: "Prepare to challenge the AI",
    explanatoryPreparationDesc: "Load an image to understand the process",
    originalImage: "Original Image",
    normalizedImage: "Normalized Image",
    neuralLayersActive: "Active Neural Layers",
    detected: "Detected",
    detectionConfidence: "Detection Confidence",
    localizationPrecision: "Localization Precision",
    minimumThreshold: "Minimum Threshold",
    duplicates: "Duplicates",
    finalResult: "Final Result",
    gesture: "Gesture",
    action: "Action",
    noHandDetected: "No Hand Detected",
    capturedImage: "Captured Image",
    cameraPreview: "Camera Preview",
    back: "Back",
    capture: "📸 Capture",
    launchAnalysis: "✅ Launch Analysis",
    backToHome: "Back to Home",
    aiFinished: "AI finished! Your turn!",
    // Dino Tutorial
    computerVisionTitle: "Computer Vision",
    whatIsComputerVision: "What is it?",
    computerVisionExplanation: "Computer vision is the ability of a machine to \"see\". Unlike us, it doesn't see an \"image\", but a grid of numbers (pixels). Its goal is to find meaning in these numbers.",
    analogy: "💡 Analogy:",
    analogyText: "It's like reading sheet music: you see symbols, but your brain hears the melody.",
    step1Skeleton: "Step 1: The Skeleton",
    handDetection: "Hand Detection",
    mediaPipeExplanation: "We use an AI called MediaPipe. It doesn't look at skin color or ring shape. It looks for 21 precise points (knuckles, wrist, fingertips).",
    tryMovingHand: "Try moving your hand!",
    detectedWithIcon: "Detected",
    waitingForHand: "Waiting...",
    raiseHand: "Raise your hand in front of the camera...",
    step2Classification: "Step 2: Classification",
    shapeRecognition: "Shape Recognition",
    shapeComparison: "The AI doesn't just measure distance. It compares the overall hand shape. It's like a child's game: \"Does this shape fit in the Open Hand or Closed Fist box?\"",
    classOpen: "CLASS: OPEN",
    classRest: "CLASS: REST (RUN)",
    open: "OPEN",
    rest: "REST",
    input: "INPUT",
    step3Action: "Step 3: Action",
    trigger: "The Trigger",
    changeDetection: "The game doesn't just look at shape, but change (Rising Edge). Action = Previous State ≠ Current State",
    actionInstruction: "Alternate \"Open Hand\" (Jump) and \"Closed Fist\" (Rest)!",
    jumps: "JUMPS",
    before: "BEFORE",
    now: "NOW",
    jump: "JUMP!!!",
    waitingAction: "WAITING FOR ACTION...",
    bonusConfidence: "Bonus: AI Confidence",
    confidenceScoreTitle: "Confidence Score",
    confidenceExplanation: "The AI sometimes doubts. It calculates a certainty percentage. If confidence is too low (e.g. < 60%), we ignore the gesture to avoid bugs.",
    confidenceLabel: "CONFIDENCE",
    visualizationMode: "VISUALIZATION_MODE: ACTIVE",
    startDinoGame: "START GAME",
    gameOver: "Game Over!",
    finalScoreLabel: "Final Score:",
    modeNotAvailable: "Mode not available",
    modeRequiresCamera: " The 'AI vs Human' mode for Dobble requires real-time camera usage.",
    modeNotSupported: "The mode \"{mode}\" is not supported.",
    dobbleDuelBoxTitle: "⚔️ AI vs Human – Dobble Duel!",
    dobbleDuelObjective: "Find the common symbol faster than the AI!",
    aiZone: "🤖 AI Zone",
    yourZone: "👤 Your Zone",
    wrongSymbol: "❌ Wrong symbol! Try again",
    changeMode: "Change Mode",
    results: "🏆 Results",
    youWon: "You won!",
    aiWon: "AI won!",
    draw: "Draw!",
    aiTime: "⏱️ AI Time",
    yourTime: "⏱️ Your Time",
    difference: "📊 Difference",
    commonSymbol: "Common Symbol",
    takePhoto: "Take a photo",
    realTime: "Real Time",
    realTimeDesc: "The AI will analyze in real-time what it sees",
    yourTurn: "Your turn!",
    gameInProgress: "Game in progress...",
    charlieDetected: "Charlie detected ✓",
    commonSymbolDetected: "Common symbol detected ✓",
    missionAccomplished: "Mission accomplished!",
    recapture: "Recapture",
    changeImage: "Change Image",
    nextMode: "Next Mode",
    aiResults: "📊 AI Results",
    confidenceScore: "Confidence Score",
    processingTime: "⏱️ Processing Time",
    detectedElements: "🎯 Detected Elements",
    // Dino Tutorial - Training Step
    step3TrainingTitle: "Brain Training",
    step3TrainingDesc: "How does AI know what an open hand is? It learned by analyzing thousands of examples!",
    trainingVsInference: "Training vs Inference",
    trainingAnalogy: "Like a student studying (Training) then taking the exam (Inference).",
    frozenModel: "Frozen Brain",
    frozenModelDesc: "The .tflite file is the final result: an optimized model that doesn't change anymore.",
    neuralNetwork: "Neural Network",
    layersExplanation: "The 42 coordinates pass through layers of mathematical neurons to calculate the final score.",
    foundPositions: "📍 Found Positions",
    bestConfidence: "🎯 Best Confidence",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [lang, setLang] = useState<Language>("fr");

  const t = (key: string): string => {
    return translations[lang][key as keyof typeof translations.fr] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
