import { createContext, useContext, useState, ReactNode } from "react";

type Language = "fr" | "en";

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  fr: {
    welcome: "🎉 Bienvenue dans l'Atelier IA Ludique !",
    subtitle: "Joue, découvre l'intelligence artificielle, et défie une IA !",
    startAdventure: "👉 Commencer l'aventure !",
    chooseGame: "🕹️ Choisis ton jeu et ton mode !",
    chooseGameSubtitle: "Chaque jeu propose 3 façons de jouer avec l'IA. À toi de choisir !",
    whereIsCharlie: "🧍 Où est Charlie",
    dobble: "🔍 Dobble",
    dinoRun: "🦖 Dino Run",
    modeAIPure: "🤖 Mode IA Pure",
    modeAIVsHuman: "🧠 Mode IA vs Humain",
    modeExplicatif: "📚 Mode Explicatif",
    descAIPure: "Laisse l'IA te montrer ce qu'elle sait faire !",
    descAIVsHuman: "Défie l'IA en duel !",
    descExplicatif: "Découvre les secrets de l'intelligence artificielle",
    descDinoAIVsHuman: "Contrôle le dinosaure avec tes gestes !",
    descDinoExplicatif: "Comprends comment l'IA détecte tes mouvements",
    launchGame: "✅ Lancer le jeu",
    backHome: "Accueil",
    selectGame: "Sélectionne un jeu pour continuer",
    selectMode: "Choisis un mode de jeu",
    gestureDetected: "Geste détecté",
    handPosition: "Position de la main",
    confidence: "Confiance",
    thresholds: "Seuils de détection",
    finalScore: "Score final",
    replay: "Rejouer",
    home: "Accueil",
    explainProcess: "Explication du processus",
    howDidAIAnalyze: "Comment l'IA a-t-elle analysé ?",
    aiProcessExplanation: "Découvre étape par étape comment l'IA a détecté l'élément",
    step: "Étape",
    next: "Suivant",
    previous: "Précédent",
    finish: "Terminer",
    step1Title: "Pré-traitement de l'image",
    step1Desc: "L'image est redimensionnée et normalisée pour optimiser la détection. Les pixels sont convertis en valeurs numériques que l'IA peut traiter.",
    step2Title: "Extraction des caractéristiques",
    step2Desc: "Un réseau de neurones convolutif (CNN) analyse l'image couche par couche pour détecter les formes, les couleurs et les textures.",
    step3Title: "Détection et localisation",
    step3Desc: "L'IA identifie les éléments dans l'image et calcule leur position exacte avec des boîtes englobantes (bounding boxes).",
    step4Title: "Classification et scoring",
    step4Desc: "Chaque élément détecté reçoit un score de confiance. Seuls les résultats dépassant un seuil minimum sont retenus.",
    step5Title: "Post-traitement",
    step5Desc: "Les détections redondantes sont supprimées et les résultats finaux sont affinés pour garantir la précision maximale.",
    analyzing: "Analyse en cours…",
    analysisComplete: "Analyse terminée !",
    aiSearching: "L'IA cherche l'élément cible…",
    aiFoundElements: "L'IA a trouvé tous les éléments !",
    continueGoodWork: "Continue comme ça !",
    explanatoryMode: "Mode Explicatif",
    explanatoryModeDebug: "Mode Explicatif - Debug",
    explanatoryModePreparation: "📚 Mode Explicatif – Préparation",
    aiPurePreparation: "🤖 Mode IA Pure – Préparation",
    aiVsHumanPreparation: "⚔️ IA vs Humain – Préparation",
    aiPurePreparationDesc: "Choisis comment l'IA va analyser ton image",
    aiVsHumanPreparationDesc: "Prépare le terrain pour défier l'IA",
    explanatoryPreparationDesc: "Charge une image pour comprendre le processus",
    originalImage: "Image originale",
    normalizedImage: "Image normalisée",
    neuralLayersActive: "Couches neuronales actives",
    detected: "Détecté",
    detectionConfidence: "Confiance détection",
    localizationPrecision: "Précision localisation",
    minimumThreshold: "Seuil minimum",
    duplicates: "Doublons",
    finalResult: "Résultat final",
    gesture: "Geste",
    action: "Action",
    noHandDetected: "Aucune main détectée",
    capturedImage: "Image capturée",
    cameraPreview: "Aperçu caméra",
    back: "Retour",
    capture: "📸 Capturer",
    launchAnalysis: "✅ Lancer l'analyse",
    backToHome: "Retour à l'accueil",
    aiFinished: "L'IA a terminé ! À toi de jouer !",
    yourTurn: "À toi de jouer !",
    gameInProgress: "Partie en cours...",
    charlieDetected: "Charlie détecté ✓",
    commonSymbolDetected: "Symbole en commun détecté ✓",
    missionAccomplished: "Mission accomplie !",
    recapture: "Recapturer",
    changeImage: "Changer d'image",
    nextMode: "Passer au mode suivant",
    aiResults: "📊 Résultats IA",
    confidenceScore: "Score de confiance",
    processingTime: "⏱️ Temps de traitement",
    detectedElements: "🎯 Éléments détectés",
    // Dino Tutorial - Training Step
    step3TrainingTitle: "L'Entraînement du Cerveau",
    step3TrainingDesc: "Comment l'IA sait ce qu'est une main ouverte ? Elle a appris en analysant des milliers d'exemples !",
    trainingVsInference: "Entraînement vs Inférence",
    trainingAnalogy: "Comme un étudiant qui révise (Entraînement) puis passe l'examen (Inférence).",
    frozenModel: "Cerveau Figé",
    frozenModelDesc: "Le fichier .tflite est le résultat final : un modèle optimisé qui ne change plus.",
    neuralNetwork: "Réseau de Neurones",
    layersExplanation: "Les 42 coordonnées traversent des couches de neurones mathématiques pour calculer le score final.",
    bestConfidence: "🎯 Meilleure confiance",
    // Dino Tutorial
    computerVisionTitle: "La Vision par Ordinateur",
    whatIsComputerVision: "Qu'est-ce que c'est ?",
    computerVisionExplanation: "La vision par ordinateur est la capacité d'une machine à \"voir\". Contrairement à nous, elle ne voit pas une \"image\", mais une grille de chiffres (pixels). Son but est de trouver du sens dans ces chiffres.",
    analogy: "💡 Analogie :",
    analogyText: "C'est comme lire une partition de musique : vous voyez des symboles, mais votre cerveau entend la mélodie.",
    step1Skeleton: "Étape 1 : IA #1 - MediaPipe",
    handDetection: "Détection de Main par IA",
    mediaPipeExplanation: "L'ordinateur ne voit pas une 'main'. Il voit des millions de pixels. Une IA spécialisée appelée MediaPipe (développée par Google) transforme automatiquement ces pixels en 21 points clés (un squelette de main).",

    // NOUVEAU : Explication du pipeline 2 IA
    aiPipelineTitle: "🔗 Pipeline : 2 IA qui travaillent ensemble",
    aiPipelineExplain: "Notre système utilise 2 intelligences artificielles en séquence : MediaPipe trouve la main et extrait les points, puis un second modèle classifie le geste.",

    // NOUVEAU : Explication de MediaPipe
    whatIsMediaPipe: "📦 Qu'est-ce que MediaPipe ?",
    mediaPipeDetail: "MediaPipe est une IA pré-entraînée par Google. Elle est spécialisée dans la détection de mains, visages, et poses corporelles. Nous l'utilisons comme 'extracteur de squelette'.",

    // NOUVEAU : Explication de l'annotation
    howWasItTrained: "🎓 Comment a-t-elle été entraînée ?",
    annotationExplain: "Des humains ont annoté (= dessiné à la main) les 21 points sur des milliers de photos de mains. C'est comme un prof qui corrige des copies : il montre à l'IA où sont les doigts, le poignet, etc. L'IA apprend en observant ces exemples.",
    annotationExample: "Exemple : Photo de main → Humain dessine les 21 points → IA apprend le pattern",

    tryMovingHand: "Essayez de bouger votre main !",
    detectedWithIcon: "Main détectée !",
    waitingForHand: "En attente de votre main...",
    cameraView: "Vue Caméra",
    skeletonView: "Vue Squelette",

    stepDataTransformation: "Étape 2 : Transformation des Données",
    fromLandmarksToNumbers: "Des Points aux Chiffres",
    dataExplanation: "Le réseau de neurones ne voit pas votre main. Il a besoin de chiffres purs. Nous convertissons les 21 points détectés par MediaPipe.",
    mathExplanation: "21 points x 2 coordonnées (X, Y) = 42 chiffres d'entrée pour l'IA #2.",
    normalizationTitle: "Normalisation",
    normalizationDesc: "On recadre les points par rapport au poignet. Ainsi, le geste fonctionne que vous soyez près, loin, à gauche ou à droite !",
    step2Classification: "Étape 2 : La Classification",
    shapeRecognition: "Reconnaissance de Forme",
    shapeComparison: "L'IA ne mesure pas juste une distance. Elle compare la forme globale de main. C'est comme un jeu d'enfant : \"Est-ce que cette forme rentre dans la boîte Main Ouverte ou Poing Fermé ?\"",
    modelLimitations: "⚠️ Limites du Modèle",
    modelLimitationsExplain: "Notre IA ne reconnaît QUE 4 gestes : Main Ouverte, Poing Fermé, Pointer, et OK. Pourquoi ? Parce qu'on ne lui a montré que les 42 coordonnées de ces 4 formes pendant l'entraînement. Si vous faites un ✌️ (victoire) ou 🤘 (rock), l'IA essaiera de le classer dans l'une des 4 catégories qu'elle connaît, même si c'est incorrect !",
    trainingDataMissing: "Données d'entraînement manquantes pour les autres gestes",
    classOpen: "CLASSE : OUVERT",
    classRest: "CLASSE : REPOS (COURIR)",
    open: "OUVERT",
    rest: "REPOS",
    input: "ENTRÉE",
    // Neural Network & Classification Updates
    neuralNetworkInputDesc: "Les 42 chiffres entrent dans la 'Couche d'Entrée' du réseau.",
    neuralNetworkOutputDesc: "Le réseau calcule 4 scores de probabilité (Ouvert, Fermé, Pointer, OK).",
    classificationProbabilities: "C'est une course ! Le score le plus haut gagne.",
    step3Action: "Étape 3 : L'Action",
    trigger: "Le Déclencheur",
    changeDetection: "Le jeu ne regarde pas juste la forme, mais le changement (Front Montant). Action = État Précédent ≠ État Actuel",
    actionInstruction: "Alternez \"Main Ouverte\" (Saut) et \"Poing Fermé\" (Repos) !",
    actionLimitation: "💡 Astuce : Si vous faites un geste inconnu (ex: ✌️), l'IA le confondra avec l'un des 4 gestes connus. Le saut peut se déclencher par erreur !",
    jumps: "SAUTS",
    before: "AVANT",
    now: "MAINTENANT",
    jump: "SAUT !!!",
    waitingAction: "EN ATTENTE D'ACTION...",
    bonusConfidence: "Bonus : Confiance de l'IA",
    confidenceScoreTitle: "Score de Confiance",
    confidenceExplanation: "L'IA doute parfois. Elle calcule un pourcentage de certitude. Si la confiance est trop basse (ex: < 60%), on ignore le geste pour éviter les bugs.",
    confidenceLabel: "CONFIANCE",
    visualizationMode: "MODE_VISUALISATION : ACTIF",
    startDinoGame: "COMMENCER LE JEU",
    gameOver: "Partie Terminée !",
    finalScoreLabel: "Score final :",
    modeNotAvailable: "Mode non disponible",
    modeRequiresCamera: "Le mode 'IA vs Humain' pour Dobble nécessite l'utilisation de la caméra en temps réel.",
    modeNotSupported: "Le mode \"{mode}\" n'est pas supporté.",
    dobbleDuelBoxTitle: "⚔️ IA vs Humain – Dobble Duel !",
    dobbleDuelObjective: "Trouve le symbole commun plus vite que l'IA !",
    aiZone: "🤖 Zone IA",
    yourZone: "👤 Ta Zone",
    wrongSymbol: "❌ Mauvais symbole ! Réessaie",
    changeMode: "Changer de mode",
    results: "🏆 Résultats",
    youWon: "Tu as gagné !",
    aiWon: "L'IA a gagné !",
    draw: "Égalité !",
    aiTime: "⏱️ Temps IA",
    yourTime: "⏱️ Ton temps",
    difference: "📊 Différence",
    commonSymbol: "Symbole commun",

    // QUIZ TRADUCTIONS
    quizTitle: "Quizz Final 🧠",
    quizIntro: "Prouve que tu es un expert en Vision par Ordinateur !",
    startQuiz: "Démarrer le Quizz",
    question: "Question",
    score: "Score",
    quizCompleted: "Bravo ! Tu as terminé le quizz.",
    quizPerfect: "Incroyable ! 100% de réussite !",
    quizGood: "Bien joué !",
    quizTryAgain: "Recommence pour améliorer ton score !",
    q1: "Comment l'ordinateur 'voit-il' ta main ?",
    q1_opt1: "Une simple photo",
    q1_opt2: "Un squelette de 21 points",
    q1_opt3: "Par magie",
    q2: "Quel geste fait sauter le Dino ?",
    q2_opt1: "Main Ouverte ✋",
    q2_opt2: "Poing Fermé ✊",
    q2_opt3: "Pouce en l'air 👍",
    q3: "Que représente le 'Score de Confiance' ?",
    q3_opt1: "La vitesse du processeur",
    q3_opt2: "La certitude de l'IA",
    q3_opt3: "La qualité de ta webcam",

    takePhoto: "Prends une photo",
    realTime: "Temps réel",
    realTimeDesc: "L'IA analysera en temps réel ce qu'elle voit",

    // Dobble Explanation Steps
    dobbleStep0Title: "Image Capturée",
    dobbleStep0Subtitle: "Le point de départ",
    dobbleStep0Desc: "Voici l'image brute que vous avez capturée. Elle contient deux cartes Dobble avec plusieurs symboles chacune.",
    dobbleStep0Details: "L'IA va maintenant analyser cette image pour identifier tous les symboles et trouver celui qui est commun aux deux cartes.",
    dobbleStep1Title: "Détection YOLO",
    dobbleStep1Subtitle: "L'IA scanne l'image",
    dobbleStep1Desc: "Le modèle YOLO (You Only Look Once) analyse toute l'image en une seule passe et détecte tous les symboles possibles.",
    dobbleStep1Details: "Chaque rectangle violet représente une détection potentielle. À cette étape, toutes les détections sont conservées, même celles avec une faible confiance.",
    dobbleStep1Analyzing: "Analyse en cours...",

    // NOUVEAU : Explication de YOLO
    whatIsYOLO: "📦 Qu'est-ce que YOLO ?",
    yoloFullName: "YOLO = 'You Only Look Once' (Tu ne regardes qu'une seule fois)",
    yoloDetail: "YOLO est une IA de détection d'objets ultra-rapide. Contrairement aux anciennes méthodes qui analysaient l'image plusieurs fois, YOLO fait tout en une seule passe. C'est pour ça qu'elle est si rapide !",

    howYOLOWorks: "⚙️ Comment ça fonctionne ?",
    yoloWorkflow: "YOLO divise l'image en grille (ex: 20x20 cellules). Chaque cellule prédit plusieurs boîtes potentielles + leurs classes. Ensuite, un filtrage (NMS) garde seulement les meilleures détections.",

    howYOLOTrained: "🎓 Comment c'est entraîné ?",
    yoloTrainingExplain: "Des humains ont annoté (dessiné des boîtes) autour de milliers d'objets dans des photos. YOLO apprend à reconnaître les patterns visuels de chaque classe. Notre modèle a été entraîné spécifiquement sur les 57 symboles Dobble !",
    yoloOurModel: "Notre modèle : dobble.pt (YOLOv8, 57 classes)",

    dobbleStep2Title: "Filtrage par Confiance",
    dobbleStep2Subtitle: "Élimination du bruit",
    dobbleStep2Desc: "Toutes les détections ne sont pas fiables. On filtre les symboles avec un score de confiance trop faible.",
    dobbleStep2ConfidenceThreshold: "Seuil de confiance :",
    dobbleStep2InitialDetections: "Détections initiales :",
    dobbleStep2AfterFiltering: "Après filtrage :",
    dobbleStep2RetainedDetections: "Détections retenues",
    dobbleStep3Title: "Comptage des Symboles",
    dobbleStep3Subtitle: "Analyse des occurrences",
    dobbleStep3Desc: "Nous comptons combien de fois chaque symbole apparaît dans l'image. Selon les règles du Dobble, le symbole commun doit apparaître exactement 2 fois.",
    dobbleStep3OccurrencesChart: "Graphique des occurrences",
    dobbleStep3TotalSymbols: "Symboles uniques détectés :",
    dobbleStep3DuplicateSymbols: "Symboles en double :",
    dobbleStep4Title: "Identification du Commun",
    dobbleStep4Subtitle: "Le symbole gagnant",
    dobbleStep4Desc: "Nous utilisons un diagramme de Venn pour visualiser les symboles de chaque carte. Le symbole à l'intersection (qui apparaît 2 fois) est le symbole commun !",
    dobbleStep4Card1: "Carte 1",
    dobbleStep4Card2: "Carte 2",
    dobbleStep4CommonSymbol: "Symbole Commun",
    dobbleStep4CommonFound: "Symbole commun trouvé :",
    dobbleStep5Title: "Localisation Précise",
    dobbleStep5Subtitle: "Positionnement exact",
    dobbleStep5Desc: "Maintenant que nous savons quel symbole chercher, l'IA affiche sa position exacte sur les deux cartes avec des boîtes englobantes.",
    dobbleStep5BothCards: "Détecté sur les deux cartes",
    dobbleStep5ConfidenceAvg: "Confiance moyenne :",
    dobbleStep6Title: "Résumé & Performance",
    dobbleStep6Subtitle: "Récapitulatif de l'analyse",
    dobbleStep6Desc: "L'analyse est terminée ! Voici un résumé complet des performances et des résultats de la détection YOLO.",
    dobbleStep6Stats: "Statistiques Finales",
    dobbleStep6TotalDetections: "Détections totales",
    dobbleStep6ProcessingTime: "Temps de traitement",
    dobbleStep6FinalConfidence: "Confiance finale",
    dobbleStep6CommonSymbolLabel: "Symbole commun identifié",
    dobbleStep6Success: "Analyse réussie !",

    // Quiz Dobble
    dobbleQuizIntro: "Testons tes connaissances sur YOLO et la détection d'objets ! 3 questions rapides t'attendent.",
    dobbleQ1: "Que signifie 'YOLO' dans le contexte de la vision par ordinateur ?",
    dobbleQ1_opt1: "Your Only Lucky Option",
    dobbleQ1_opt2: "You Only Look Once",
    dobbleQ1_opt3: "Yellow Object Location Output",
    dobbleQ2: "Que représente une 'bounding box' (boîte englobante) ?",
    dobbleQ2_opt1: "Un rectangle autour d'un objet détecté",
    dobbleQ2_opt2: "La couleur de l'objet",
    dobbleQ2_opt3: "Le nom du fichier image",
    dobbleQ3: "Comment trouve-t-on le symbole commun entre deux cartes Dobble ?",
    dobbleQ3_opt1: "En choisissant au hasard",
    dobbleQ3_opt2: "En comparant les tailles",
    dobbleQ3_opt3: "En comptant quel symbole apparaît 2 fois"
  },
  en: {
    welcome: "🎉 Welcome to the AI Fun Workshop!",
    subtitle: "Play, discover artificial intelligence, and challenge an AI!",
    startAdventure: "👉 Start the adventure!",
    chooseGame: "🕹️ Choose your game and mode!",
    chooseGameSubtitle: "Each game offers 3 ways to play with AI. Your choice!",
    whereIsCharlie: "🧍 Where's Waldo",
    dobble: "🔍 Dobble",
    dinoRun: "🦖 Dino Run",
    modeAIPure: "🤖 Pure AI Mode",
    modeAIVsHuman: "🧠 AI vs Human Mode",
    modeExplicatif: "📚 Explanatory Mode",
    descAIPure: "Let the AI show you what it can do!",
    descAIVsHuman: "Challenge the AI in a duel!",
    descExplicatif: "Discover the secrets of artificial intelligence",
    descDinoAIVsHuman: "Control the dinosaur with your gestures!",
    descDinoExplicatif: "Understand how AI detects your movements",
    launchGame: "✅ Launch game",
    backHome: "Home",
    selectGame: "Select a game to continue",
    selectMode: "Choose a game mode",
    gestureDetected: "Gesture detected",
    handPosition: "Hand position",
    confidence: "Confidence",
    thresholds: "Detection thresholds",
    finalScore: "Final score",
    replay: "Replay",
    home: "Home",
    explainProcess: "Process Explanation",
    howDidAIAnalyze: "How did the AI analyze?",
    aiProcessExplanation: "Discover step by step how the AI detected the element",
    step: "Step",
    next: "Next",
    previous: "Previous",
    finish: "Finish",
    step1Title: "Image Preprocessing",
    step1Desc: "The image is resized and normalized to optimize detection. Pixels are converted into numerical values that the AI can process.",
    step2Title: "Feature Extraction",
    step2Desc: "A Convolutional Neural Network (CNN) analyzes the image layer by layer to detect shapes, colors, and textures.",
    step3Title: "Detection and Localization",
    step3Desc: "The AI identifies elements in the image and calculates their exact position with bounding boxes.",
    step4Title: "Classification and Scoring",
    step4Desc: "Each detected element receives a confidence score. Only results exceeding a minimum threshold are retained.",
    step5Title: "Post-processing",
    step5Desc: "Redundant detections are removed and final results are refined to ensure maximum accuracy.",
    analyzing: "Analyzing…",
    analysisComplete: "Analysis Complete!",
    aiSearching: "The AI is searching for the target element…",
    aiFoundElements: "The AI has found all elements!",
    continueGoodWork: "Keep it up!",
    explanatoryMode: "Explanatory Mode",
    explanatoryModeDebug: "Explanatory Mode - Debug",
    explanatoryModePreparation: "📚 Explanatory Mode – Preparation",
    aiPurePreparation: "🤖 Pure AI Mode – Preparation",
    aiVsHumanPreparation: "⚔️ AI vs Human – Preparation",
    aiPurePreparationDesc: "Choose how the AI will analyze your image",
    aiVsHumanPreparationDesc: "Prepare to challenge the AI",
    explanatoryPreparationDesc: "Load an image to understand the process",
    originalImage: "Original Image",
    normalizedImage: "Normalized Image",
    neuralLayersActive: "Active Neural Layers",
    detected: "Detected",
    detectionConfidence: "Detection Confidence",
    localizationPrecision: "Localization Precision",
    minimumThreshold: "Minimum Threshold",
    duplicates: "Duplicates",
    finalResult: "Final Result",
    gesture: "Gesture",
    action: "Action",
    noHandDetected: "No Hand Detected",
    capturedImage: "Captured Image",
    cameraPreview: "Camera Preview",
    back: "Back",
    capture: "📸 Capture",
    launchAnalysis: "✅ Launch Analysis",
    backToHome: "Back to Home",
    aiFinished: "AI finished! Your turn!",
    // Dino Tutorial
    computerVisionTitle: "Computer Vision",
    whatIsComputerVision: "What is it?",
    computerVisionExplanation: "Computer vision is the ability of a machine to \"see\". Unlike us, it doesn't see an \"image\", but a grid of numbers (pixels). Its goal is to find meaning in these numbers.",
    analogy: "💡 Analogy:",
    analogyText: "It's like reading sheet music: you see symbols, but your brain hears the melody.",
    step1Skeleton: "Step 1: AI #1 - MediaPipe",
    handDetection: "AI Hand Detection",
    mediaPipeExplanation: "The computer doesn't see a 'hand'. It sees millions of pixels. A specialized AI called MediaPipe (developed by Google) automatically transforms these pixels into 21 key points (a hand skeleton).",

    // NEW: 2 AI Pipeline explanation
    aiPipelineTitle: "🔗 Pipeline: 2 AIs working together",
    aiPipelineExplain: "Our system uses 2 artificial intelligences in sequence: MediaPipe finds the hand and extracts points, then a second model classifies the gesture.",

    // NEW: MediaPipe explanation
    whatIsMediaPipe: "📦 What is MediaPipe?",
    mediaPipeDetail: "MediaPipe is a pre-trained AI by Google. It specializes in detecting hands, faces, and body poses. We use it as a 'skeleton extractor'.",

    // NEW: Annotation explanation
    howWasItTrained: "🎓 How was it trained?",
    annotationExplain: "Humans annotated (= manually drew) the 21 points on thousands of hand photos. It's like a teacher grading papers: they show the AI where the fingers, wrist, etc. are. The AI learns by observing these examples.",
    annotationExample: "Example: Hand photo → Human draws 21 points → AI learns the pattern",

    tryMovingHand: "Try moving your hand!",
    detectedWithIcon: "Hand detected!",
    waitingForHand: "Waiting for your hand...",
    cameraView: "Camera View",
    skeletonView: "Skeleton View",

    stepDataTransformation: "Step 2: Data Transformation",
    fromLandmarksToNumbers: "From Points to Numbers",
    dataExplanation: "The neural network doesn't see your hand. It needs pure numbers. We convert the 21 points detected by MediaPipe.",
    mathExplanation: "21 points x 2 coordinates (X, Y) = 42 input numbers for AI #2.",
    normalizationTitle: "Normalization",
    normalizationDesc: "We crop points relative to the wrist. So the gesture works whether you are near, far, left, or right!",
    // The original code had a duplicate `waitingForHand` and `raiseHand` here.
    step2Classification: "Step 2: Classification",
    shapeRecognition: "Shape Recognition",
    shapeComparison: "The AI doesn't just measure distance. It compares the overall hand shape. It's like a child's game: \"Does this shape fit in the Open Hand or Closed Fist box?\"",
    modelLimitations: "⚠️ Model Limitations",
    modelLimitationsExplain: "Our AI recognizes ONLY 4 gestures: Open Hand, Closed Fist, Pointer, and OK. Why? Because we only showed it the 42 coordinates of these 4 shapes during training. If you make a ✌️ (victory) or 🤘 (rock) sign, the AI will try to classify it into one of the 4 categories it knows, even if it's incorrect!",
    trainingDataMissing: "Training data missing for other gestures",
    classOpen: "CLASS: OPEN",
    classRest: "CLASS: REST (RUN)",
    open: "OPEN",
    rest: "REST",
    input: "INPUT",
    // Neural Network & Classification Updates
    neuralNetworkInputDesc: "The 42 numbers enter the 'Input Layer' of the network.",
    neuralNetworkOutputDesc: "The network calculates 4 probability scores (Open, Closed, Pointer, OK).",
    classificationProbabilities: "It's a race! The highest score wins.",
    step3Action: "Step 3: Action",
    trigger: "The Trigger",
    changeDetection: "The game doesn't just look at the shape, but the change (Rising Edge). Action = Previous State ≠ Current State",
    actionInstruction: "Alternate between \"Open Hand\" (Jump) and \"Closed Fist\" (Rest)!",
    actionLimitation: "💡 Tip: If you make an unknown gesture (e.g., ✌️), the AI will confuse it with one of the 4 known gestures. The jump may trigger by mistake!",
    jumps: "JUMPS",
    before: "BEFORE",
    now: "NOW",
    jump: "JUMP!!!",
    waitingAction: "WAITING FOR ACTION...",
    bonusConfidence: "Bonus: AI Confidence",
    confidenceScoreTitle: "Confidence Score",
    confidenceExplanation: "The AI sometimes doubts. It calculates a certainty percentage. If confidence is too low (e.g. < 60%), we ignore the gesture to avoid bugs.",
    confidenceLabel: "CONFIDENCE",
    visualizationMode: "VISUALIZATION_MODE: ACTIVE",
    startDinoGame: "START GAME",
    gameOver: "Game Over!",
    finalScoreLabel: "Final Score:",
    modeNotAvailable: "Mode not available",
    modeRequiresCamera: " The 'AI vs Human' mode for Dobble requires real-time camera usage.",
    modeNotSupported: "The mode \"{mode}\" is not supported.",
    dobbleDuelBoxTitle: "⚔️ AI vs Human – Dobble Duel!",
    dobbleDuelObjective: "Find the common symbol faster than the AI!",
    aiZone: "🤖 AI Zone",
    yourZone: "👤 Your Zone",
    wrongSymbol: "❌ Wrong symbol! Try again",
    changeMode: "Change Mode",
    results: "🏆 Results",
    youWon: "You won!",
    aiWon: "AI won!",
    draw: "Draw!",
    aiTime: "⏱️ AI Time",
    yourTime: "⏱️ Your Time",
    difference: "📊 Difference",
    commonSymbol: "Common Symbol",

    // QUIZ TRANSLATIONS
    quizTitle: "Final Quiz 🧠",
    quizIntro: "Prove you're a Computer Vision expert!",
    startQuiz: "Start Quiz",
    question: "Question",
    score: "Score",
    quizCompleted: "Congrats! You finished the quiz.",
    quizPerfect: "Amazing! 100% correct!",
    quizGood: "Well done!",
    quizTryAgain: "Try again to improve your score!",
    q1: "How does the computer 'see' your hand?",
    q1_opt1: "A simple photo",
    q1_opt2: "A 21-point skeleton",
    q1_opt3: "By magic",
    q2: "Which gesture makes the Dino jump?",
    q2_opt1: "Open Hand ✋",
    q2_opt2: "Closed Fist ✊",
    q2_opt3: "Thumbs Up 👍",
    q3: "What does the 'Confidence Score' represent?",
    q3_opt1: "Processor speed",
    q3_opt2: "AI certainty",
    q3_opt3: "Webcam quality",

    takePhoto: "Take a photo",
    realTime: "Real Time",
    realTimeDesc: "The AI will analyze in real-time what it sees",

    // Dobble Explanation Steps
    dobbleStep0Title: "Captured Image",
    dobbleStep0Subtitle: "The starting point",
    dobbleStep0Desc: "Here is the raw image you captured. It contains two Dobble cards with several symbols each.",
    dobbleStep0Details: "The AI will now analyze this image to identify all symbols and find the one that is common to both cards.",
    dobbleStep1Title: "YOLO Detection",
    dobbleStep1Subtitle: "AI scanning the image",
    dobbleStep1Desc: "The YOLO model (You Only Look Once) analyzes the entire image in a single pass and detects all possible symbols.",
    dobbleStep1Details: "Each purple rectangle represents a potential detection. At this stage, all detections are kept, even those with low confidence.",
    dobbleStep1Analyzing: "Analyzing...",

    // NEW: YOLO Explanation
    whatIsYOLO: "📦 What is YOLO?",
    yoloFullName: "YOLO = 'You Only Look Once'",
    yoloDetail: "YOLO is an ultra-fast object detection AI. Unlike old methods that analyzed images multiple times, YOLO does everything in a single pass. That's why it's so fast!",

    howYOLOWorks: "⚙️ How does it work?",
    yoloWorkflow: "YOLO divides the image into a grid (e.g., 20x20 cells). Each cell predicts several potential boxes + their classes. Then, filtering (NMS) keeps only the best detections.",

    howYOLOTrained: "🎓 How is it trained?",
    yoloTrainingExplain: "Humans annotated (drew boxes) around thousands of objects in photos. YOLO learns to recognize the visual patterns of each class. Our model was trained specifically on the 57 Dobble symbols!",
    yoloOurModel: "Our model: dobble.pt (YOLOv8, 57 classes)",

    dobbleStep2Title: "Confidence Filtering",
    dobbleStep2Subtitle: "Noise elimination",
    dobbleStep2Desc: "Not all detections are reliable. We filter symbols with a confidence score that is too low.",
    dobbleStep2ConfidenceThreshold: "Confidence threshold:",
    dobbleStep2InitialDetections: "Initial detections:",
    dobbleStep2AfterFiltering: "After filtering:",
    dobbleStep2RetainedDetections: "Retained Detections",
    dobbleStep3Title: "Symbol Counting",
    dobbleStep3Subtitle: "Occurrence analysis",
    dobbleStep3Desc: "We count how many times each symbol appears in the image. According to Dobble rules, the common symbol must appear exactly 2 times.",
    dobbleStep3OccurrencesChart: "Occurrences Chart",
    dobbleStep3TotalSymbols: "Unique symbols detected:",
    dobbleStep3DuplicateSymbols: "Duplicate symbols:",
    dobbleStep4Title: "Common Symbol Identification",
    dobbleStep4Subtitle: "The winning symbol",
    dobbleStep4Desc: "We use a Venn diagram to visualize the symbols of each card. The symbol at the intersection (appearing 2 times) is the common symbol!",
    dobbleStep4Card1: "Card 1",
    dobbleStep4Card2: "Card 2",
    dobbleStep4CommonSymbol: "Common Symbol",
    dobbleStep4CommonFound: "Common symbol found:",
    dobbleStep5Title: "Precise Localization",
    dobbleStep5Subtitle: "Exact positioning",
    dobbleStep5Desc: "Now that we know which symbol to look for, the AI displays its exact position on both cards with bounding boxes.",
    dobbleStep5BothCards: "Detected on both cards",
    dobbleStep5ConfidenceAvg: "Average confidence:",
    dobbleStep6Title: "Summary & Performance",
    dobbleStep6Subtitle: "Analysis recap",
    dobbleStep6Desc: "The analysis is complete! Here is a full summary of YOLO detection performance and results.",
    dobbleStep6Stats: "Final Statistics",
    dobbleStep6TotalDetections: "Total detections",
    dobbleStep6ProcessingTime: "Processing time",
    dobbleStep6FinalConfidence: "Final confidence",
    dobbleStep6CommonSymbolLabel: "Common symbol identified",
    dobbleStep6Success: "Analysis successful!",

    // Quiz Dobble
    dobbleQuizIntro: "Let's test your knowledge about YOLO and object detection! 3 quick questions await you.",
    dobbleQ1: "What does 'YOLO' mean in computer vision?",
    dobbleQ1_opt1: "Your Only Lucky Option",
    dobbleQ1_opt2: "You Only Look Once",
    dobbleQ1_opt3: "Yellow Object Location Output",
    dobbleQ2: "What does a 'bounding box' represent?",
    dobbleQ2_opt1: "A rectangle around a detected object",
    dobbleQ2_opt2: "The color of the object",
    dobbleQ2_opt3: "The image file name",
    dobbleQ3: "How do we find the common symbol between two Dobble cards?",
    dobbleQ3_opt1: "By choosing randomly",
    dobbleQ3_opt2: "By comparing sizes",
    dobbleQ3_opt3: "By counting which symbol appears twice",

    yourTurn: "Your turn!",
    gameInProgress: "Game in progress...",
    charlieDetected: "Charlie detected ✓",
    commonSymbolDetected: "Common symbol detected ✓",
    missionAccomplished: "Mission accomplished!",
    recapture: "Recapture",
    changeImage: "Change Image",
    nextMode: "Next Mode",
    aiResults: "📊 AI Results",
    confidenceScore: "Confidence Score",
    processingTime: "⏱️ Processing Time",
    detectedElements: "🎯 Detected Elements",
    // Dino Tutorial - Training Step
    step3TrainingTitle: "Brain Training",
    step3TrainingDesc: "How does AI know what an open hand is? It learned by analyzing thousands of examples!",
    trainingVsInference: "Training vs Inference",
    trainingAnalogy: "Like a student studying (Training) then taking the exam (Inference).",
    frozenModel: "Frozen Brain",
    frozenModelDesc: "The .tflite file is the final result: an optimized model that doesn't change anymore.",
    neuralNetwork: "Neural Network",
    layersExplanation: "The 42 coordinates pass through layers of mathematical neurons to calculate the final score.",
    foundPositions: "📍 Found Positions",
    bestConfidence: "🎯 Best Confidence",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [lang, setLang] = useState<Language>("fr");

  const t = (key: string): string => {
    return translations[lang][key as keyof typeof translations.fr] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
